export const dynamic = 'force-static';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../context/CartContext";
import Chatbot from "../components/layout/Chatbot";
import Protection from "../components/layout/Protection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deero Advert",
  description: "Generated by create next app",
  icons: {
    icon: "/1-2.jpg?v=final",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (window.location.hostname !== 'localhost') {
                setInterval(function() {
                  console.clear();
                  debugger;
                }, 500);
              }
            `,
          }}
        />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <Protection />
        <CartProvider>
          {children}
        </CartProvider>
        <Chatbot />
      </body>
    </html>
  );
}

